### ISSUE TITLE
Deployment checklist

### ISSUE THREAD

**Issue by tomdoel** [alan-turing-institute/data-classification-app#106]
Before the first production deployment conduct a review:
- [x] Review [Django deployment checklist](https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/)
- [x] Review Azure configuration settings to ensure production-ready   
- [x] Review Django configuration settings to ensure production-ready  
- [x] Review npm audit for security vulnerabilities
