### ISSUE TITLE
First pass of bugs

### ISSUE THREAD

**Issue by JulesMarz** [alan-turing-institute/data-classification-app#14]
- [ ] Project settings: Cannot change name of project once set - #8 
- [ ] Cannot delete a project (or at least request for deletion) - #8 
- [x] Adding erroneous usernames adds the role and an instance for that role but doesn't save username? - #16
- [ ] Will data providers be uploading data through this app?
- [ ] Logging out doesn't seem to log me out (I can log back in in incognito mode without being challenged, I can log in without being challenged in a separate incognito more window, if the other one is open). Only solution is to close the incognito browser and restart) - #17
- [ ] Can only add users as syscontroller, Not research  coordinator - #18
- [x] Editing user:  deleting *all* the projects/roles, causes server error (500) - #19
- [ ] valid phone number needs country code (this is good, but it should probably say this) - #20
- [x] data classification - Step 4 doesn't have a continue button (cannot proceed) (I was trying to get a tier 3  result...) - #21
- [x] Project Double Chocolate mini bites: Added all 3 users as a research coordinator - It seems to have lost my (jules.manser) user, but it is still there (cannot add again). This was showing as null. I have deleted and re added as a different role - #27 
- [x] Project Double Chocolate mini bites:3 reviews of classification  (all tier 2) doesn't return an overall classification (test user and sys controller are classified as "research coordinator" and jules.masner is data owner) - syscontroller not showing as research coordinator (see output below) - #28 

>Data Classification for Double Chocolate mini bites
You have classified this project as Tier 2

>syscontroller2@dsgroupdev.co.uk () classified the project as Tier 2
test-user-1@dsgroupdev.co.uk (Research Coordinator) classified the project as Tier 2
Overall classification
Classification incomplete`
